### ISSUE TITLE
Request to support building ktlint using gradle

### ISSUE THREAD

**Issue by liutikas** [shyiko/ktlint#102]
We have starting using ktlint for Android support library. Due to internal policy we have to build all the tools we using Google build infrastructure and sadly maven is not on a list of supported build systems. To get around that I have written Gradle build files in our local fork of your library so it can be build with Gradle. Would you consider taking these build.gradle files as a pull request? I would provide all of them and I can be on the hook for fixing them up as your dependencies change. This way we don't have to have to have locally forked files.

**Comment by shyiko** [comment]
Absolutely. Whatever you guys need.

**Comment by shyiko** [comment]
Alright, I'm closing this issue as there is nothing actionable here but please do send the PR whenever it's ready (and if there is anything I can help with - please let me know).
