### ISSUE TITLE
no-empty-class-body auto-correction leaves spacing when file ends with {}

### ISSUE THREAD

**Issue by thauk-copperleaf** [shyiko/ktlint#109]
I am trying to write a test case for a bug I found, but I'm on Windows 7, and I've just noticed that there's a hardcoded expectations in the unit tests that the line terminators are `\n`. Is this already known & expected?

**Comment by thauk-copperleaf** [comment]
The bug in question is that the `NoEmptyClassBodyRule` does not remove whitespace between the declaration and the block if the block is not terminated by a newline.

i.e. if you have:
    `"fun main() {\n}"`
you expect the rule to format this to:
    `"fun main()"`
but you get:
    `"fun main() "`

Which means if you ran ktlint again, `NoTrailingSpacesRuleTest` would cause it to fail.

**Comment by shyiko** [comment]
Thank you, @thauk-copperleaf. This particular issue is fixed.
As for line terminators, [ktlint is forcing \n regardless of the OS](https://github.com/shyiko/ktlint/blob/master/ktlint-core/src/main/kotlin/com/github/shyiko/ktlint/core/KtLint.kt#L232). CI on Windows will be taken care of in https://github.com/shyiko/ktlint/issues/110.

**Comment by thauk-copperleaf** [comment]
@shyiko I had the same code change pending but I didn't want to submit a PR without a unit test :) Thanks for the fix :)

**Comment by thauk-copperleaf** [comment]
@shyiko As for the forcing `\n`, it wasn't working on my system. I double-checked that I was at the same commit as the last Travis build, and I am, but the tests don't pass (at least `NoEmptyClassBodyRuleTest`) on Windows 7 :(

**Comment by shyiko** [comment]
@thauk-copperleaf tests on Windows are now green (https://ci.appveyor.com/project/shyiko/ktlint/build/master.3) (#110 resolved).

**Comment by thauk-copperleaf** [comment]
@shyiko Thanks for the quick replies! BTW, any plans for a "missing newline at end of file" rule? Many tools warn/error about that (including git).

**Comment by shyiko** [comment]
@thauk-copperleaf it's supported but not enabled by default (https://github.com/shyiko/ktlint/issues/103). We plan to change in the next release.

**Comment by thauk-copperleaf** [comment]
@shyiko Excellent! Thanks!
