### ISSUE TITLE
Should ktlint catch "Java-isms" like Optional<Foo>, arrayListOf() and similar?

### ISSUE THREAD

**Issue by project-flashlight** [shyiko/ktlint#114]
I'm by no means a Kotlin expert, but I understand that absent some special cases (Java interop?) Java's `Optional<Foo>` type should not be used, in favour of Kotlin's `Foo?`. Similarly Kotlin's `listOf()` and `mutableListOf()` (and similar for other collections) should be preferred over `arrayListOf()`.

Is it `ktlint`'s role to catch things like this?

**Comment by vRallev** [comment]
I vote against this. And `Optional` is very helpful also in Kotlin.

**Comment by shyiko** [comment]
The primary focus of ktlint is code style. Forcing user to (or not to) use specific API is out of scope I'm afraid. But, you can always add your own rules if you want to (https://github.com/shyiko/ktlint#can-i-have-my-own-rules-on-top-of-ktlint).

**Comment by ratkins** [comment]
Ok, fair enough.
