### ISSUE TITLE
Indent for parameter list. Should it be configurable?

### ISSUE THREAD

**Issue by MyDogTom** [shyiko/ktlint#119]
IntelliJ allows to chose between "indent" and "continuation indent" for parameter list.
![screen shot 2017-12-04 at 11 18 25](https://user-images.githubusercontent.com/5940462/33548510-a98afb4e-d8e7-11e7-8a50-e4c4fec63ac8.png)

As I understand, by default "continuation indent" is used. From other side, Google and Jetbrains [suggest to use indent](https://github.com/android/kotlin-guides/issues/37) and not continuation indent.

**Question**: Should Ktlint support both approaches or support only one "recommended" way?

Advantage of supporting only one way: follow Ktlint's ideology. 
Advantage of supporting both approaches: easier adaption for all people. For example, in my project we use continuation indent for parameters.

**Comment by shyiko** [comment]
@MyDogTom If both JetBrains and Android Team agreed to use single indent in parameter lists I'd say we should too (especially that we claim <b>"that ktlint tries to capture (reflect) official code style from kotlinlang.org and Android Kotlin Style Guide"</b> in the README).

**Comment by MyDogTom** [comment]
Fair enough.

**Comment by shyiko** [comment]
Let's keep this ticket open as a reminder that `ktlint --apply-to-idea` needs to be updated to turn "Use continuation indent in parameter lists" off by default.

**Comment by vanniktech** [comment]
Was this done already? Or does this still need to be added?

**Comment by shyiko** [comment]
@vanniktech needs to be added (https://github.com/shyiko/ktlint/blob/master/ktlint/src/main/kotlin/com/github/shyiko/ktlint/internal/IntellijIDEAIntegration.kt)

**Comment by shyiko** [comment]
Done in [0.16.0](https://github.com/shyiko/ktlint/releases/tag/0.16.0).
