### ISSUE TITLE
Default continuation indent for Android should be 8 not 4

### ISSUE THREAD

**Issue by MyDogTom** [shyiko/ktlint#120]
This [commit](https://github.com/shyiko/ktlint/commit/ed261175241807e0f7bb0428db8f2d0c253f6e5e) changes continuation indent from 8 to 4. 
According to Android Kotlin style guide it [should be 8](https://android.github.io/kotlin-guides/style.html#continuation-indent).
I guess confusion comes from https://github.com/android/kotlin-guides/issues/37. But that issue is about usage of "indent" instead of "continuation indent" for parameter list. Not about changing the size of continuation indent.

**Comment by shyiko** [comment]
@MyDogTom right. Thanks for pointing it out.

**Comment by vanniktech** [comment]
I think this was recently changed to be 4.

They wanted to have the fields in classes aligned with everything else and hence they made that change. https://github.com/android/kotlin-guides/issues/37

**Comment by shyiko** [comment]
@vanniktech see latest https://github.com/android/kotlin-guides/blob/master/style.md#continuation-indent. @MyDogTom is right. Android Kotlin Style Guide prescribes +8 continuation indentation (+4 for parameters).

**Comment by scottkennedy** [comment]
"Android Kotlin Style Guide prescribes +8 continuation indentation (+4 for parameters)."

Is there a way to specify that in IntelliJ / Android Studio?  The "continuation indent" setting seems to control both.

**Comment by shyiko** [comment]
@scottkennedy see https://github.com/shyiko/ktlint/pull/134#issuecomment-369021113

**Comment by shyiko** [comment]
https://github.com/shyiko/ktlint/issues/308
