### ISSUE TITLE
formatting for "if - else - if"

### ISSUE THREAD

**Issue by MyDogTom** [shyiko/ktlint#122]
Ktlint allows the following formatting
```kotlin
fun funA() {
    if (conditionA()) {
        doSomething()
    } else 
    if (conditionB()) {
        doAnotherThing()
    }
}
```
there is [real example](https://github.com/shyiko/ktlint/blob/master/ktlint-core/src/test/kotlin/com/github/shyiko/ktlint/core/KtLintTest.kt#L19)

From my point of view, such formatting is a bit confusing (second `if` can be perceived as completely independent)

**Proposal 1**
Forbid line break between `else` and `if`
```kotlin
fun funA() {
    if (conditionA()) {
        doSomething()
    } else if (conditionB()) {
        doAnotherThing()
    }
}
```

**Proposal 2** (doesn't make sense, if first proposal is accepted)
Teach `indentionRule` to enforce indent after `else`

```kotlin
fun funA() {
    if (conditionA()) {
        doSomething()
    } else
        if (conditionB()) {
            doAnotherThing()
        }
}
```

Personally, I would prefer the first one.  I'm happy to implement it, if such PR is welcome.

**Comment by shyiko** [comment]
First proposal looks reasonable (and consistent with https://android.github.io/kotlin-guides/style.html examples). 

Go ahead (and thank you :bowing_man:).
