### ISSUE TITLE
Unresolved dependency kolor:0.0.2

### ISSUE THREAD

**Issue by KrysKruk** [shyiko/ktlint#124]
Hi!

When installing newest ktlint version 0.14.0 I just copied the requirements from https://ktlint.github.io/ into my `build.gradle` file.

Installation doesn't work because of unresolved dependency:
```
Execution failed for task ':ktlint'.
> Could not resolve all files for configuration ':ktlint'.
   > Could not find com.andreapivetta.kolor:kolor:0.0.2.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/andreapivetta/kolor/kolor/0.0.2/kolor-0.0.2.pom
         https://repo1.maven.org/maven2/com/andreapivetta/kolor/kolor/0.0.2/kolor-0.0.2.jar

     Required by:
         project : > com.github.shyiko:ktlint:0.14.0 > com.github.shyiko.ktlint:ktlint-reporter-plain:0.14.0
         project : > com.github.shyiko:ktlint:0.14.0 > com.github.shyiko.ktlint:ktlint-test:0.14.0
```

This dependency as shows on GitHub project https://github.com/ziggy42/kolor requires `jcenter` repository.

Installation works after adding `jcenter()` into dependencies.

**Comment by shyiko** [comment]
Thank you, @KrysKruk. README updated.
