### ISSUE TITLE
Using values of output displayed

### ISSUE THREAD

**Issue by parimatrix** [shyiko/ktlint#127]
Hi ! When I run ktlint on a file, I see the filename , line, col & the detail on the cmd. Now I wish to use the values of these somewhere else after running this. How can I access these values for each LintError! Any info would be of great help. Thanks a lot. 
PS: Could not find any channel, so asking here. Thanks once again !

**Comment by shyiko** [comment]
Try something like `ktlint --reporter=plain --reporter=json,output=ktlint.json` (this will generate `ktlint.json` file containing lint errors) or https://github.com/shyiko/ktlint#usage.
