### ISSUE TITLE
False positive unused import for operator overloads

### ISSUE THREAD

**Issue by dsvoronin** [shyiko/ktlint#13]
Seems like unused import check not aware of operator overloading. 

`import rx.lang.kotlin.plusAssign` - marked as unused by ktlint

actual usage in same file
` presenterLifecycleSubscription += resetClicks.subscribe { resetSelection() }`

**Comment by shyiko** [comment]
@dsvoronin both #12 and #13 are fixed in 0.2.0 that I'm planning to push within the next couple of hours. Thank you for reporting these. Much appreciated :bow:.

**Comment by shyiko** [comment]
@dsvoronin 0.2.0 is out (see [release notes](https://github.com/shyiko/ktlint/blob/master/changelog.md)).

P.S. took a little bit longer than a few hours but at least it's the same day :)
