### ISSUE TITLE
Imports used only by KDocs are removed

### ISSUE THREAD

**Issue by magneticflux-** [shyiko/ktlint#133]
I have some KDocs that [refer to classes by imports](https://kotlinlang.org/docs/reference/kotlin-doc.html#linking-to-elements) instead of fully qualified names and ktlint removes the imports because no code uses them.

I'm using Spotless 3.7.0 for ktlint.

**Comment by shyiko** [comment]
Hi @magneticflux-. 

Could you please provide an example? We have a few tests that verify that this doesn't happen - https://github.com/shyiko/ktlint/blob/master/ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/NoUnusedImportsRuleTest.kt#L163 but it's possible we missed something.

**Comment by magneticflux-** [comment]
Ah, the default version of ktlint used by Spotless is [nowhere near](https://github.com/diffplug/spotless/blob/8772ea6e1e6596f6d60a2562dba908dbe8f2e6ab/lib/src/main/java/com/diffplug/spotless/kotlin/KtLintStep.java#L37) the current release. After forcing it to use the newest one it works just fine now. I'll raise an issue with Spotless to update their default version of ktlint.
