### ISSUE TITLE
Ktlint error message are logged as QUIET

### ISSUE THREAD

**Issue by maxTanquerel** [shyiko/ktlint#135]
Hi everyone,

By default, in the console, ktlint errors are logged as QUIET on the console. Is it possible to display them as ERROR ?

It will be easier to catch them in log on build server.

Thank you,

Max

**Comment by shyiko** [comment]
Hi Max.
If by QUITE you mean stdout and ERROR stderr then you can do it with something like `ktlint >&2` or `ktlint --reporter=plain,output=/dev/stderr`. Let me know if this is not what you're asking.

**Comment by maxTanquerel** [comment]
Hi shyiko, 
Thank you for the quick answer. 
Not really, what I meant is, in the gradle console there is that kind of lines that explain where is the error:
```
18:02:35.371 [QUIET] [system.out] /[MyFilePath].kt
18:02:35.371 [QUIET] [system.out]   7:1 Needless blank line(s)
```

My question is : Is it possible (with some configuration with the reporter maybe) to display them as ERROR, so they will be in red and easy to catch up in the gradle console.

I know that you can send the report to a specific file but it's not what I am looking for.

Thx again

**Comment by shyiko** [comment]
I see. If you are using one of the gradle plugins - you might want to take that question to the plugin author(s). If not - try changing [standardOutput](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html) to System.err (in the ktlint gradle task) (I haven't tried that myself so I'm not sure whether that's going to work or not).

**Comment by maxTanquerel** [comment]
Very nice, good idea. This is working for me.
Thank you very much
