### ISSUE TITLE
Push out new release? 

### ISSUE THREAD

**Issue by plastiv** [shyiko/ktlint#138]
It's blocking kotlin `1.1.20` update for us, which I see is already handled in trunk.

**Comment by MyDogTom** [comment]
@shyiko I'm pretty sure @plastiv is talking about 1.2.20 and this PR: https://github.com/shyiko/ktlint/pull/132 

Kotlin 1.2.20 versions is [released today](https://github.com/JetBrains/kotlin/releases/tag/v1.2.20)

**Comment by plastiv** [comment]
My bad, sorry for the confusion. Yes, I meant release with this fix included https://github.com/shyiko/ktlint/issues/131

**Comment by shyiko** [comment]
[0.15.0](https://github.com/shyiko/ktlint/blob/master/CHANGELOG.md#0150---2018-01-18) released :tada: .  
@MyDogTom, thank you for all the changes!
