### ISSUE TITLE
failed from maven

### ISSUE THREAD

**Issue by stalexxx** [shyiko/ktlint#140]
I've done maven setup like it is written and got this. Standalone linter works great!

ktlint:
   [ktlint] Exception in thread "main" java.lang.VerifyError: Uninitialized object exists on backward branch 191
   [ktlint] Exception Details:
   [ktlint]   Location:
   [ktlint]     com/github/shyiko/ktlint/Main.buildDependencyResolver()Lcom/github/shyiko/ktlint/internal/MavenDependencyResolver; @408: goto
   [ktlint]   Reason:
   [ktlint]     Error exists in the bytecode
   [ktlint]   Bytecode:
   [ktlint]     0000000: bb00 e159 bb00 e159 1304 69b8 046c 1304
   [ktlint]     0000010: 7db7 03c2 1304 7fb7 03cd 4c2b b803 c8bb
   [ktlint]     0000020: 0481 592b 06bd 0483 5903 bb04 8559 1304
   [ktlint]     0000030: 8713 0489 1304 8bb7 048e bb04 9059 0313
   [ktlint]     0000040: 0492 1304 94b7 0497 b604 9bb6 049f 5359
   [ktlint]     0000050: 04bb 0485 5913 04a1 1304 8913 04a3 b704
   [ktlint]     0000060: 8ebb 0490 5903 1304 9213 0494 b704 97b6
   [ktlint]     0000070: 049b b604 9f53 5905 bb04 8559 1304 a513
   [ktlint]     0000080: 0489 1304 a7b7 048e b604 9f53 b804 aac0
   [ktlint]     0000090: 009e b204 acc0 0091 4e3a 143a 133a 123a
   [ktlint]     00000a0: 112d 3a04 bb00 9359 2d10 0ab8 0099 b700
   [ktlint]     00000b0: 9cc0 009e 3a05 1904 b900 a201 003a 0619
   [ktlint]     00000c0: 06b9 00a8 0100 9900 d519 06b9 00ac 0100
   [ktlint]     00000d0: 3a07 1905 1907 c000 893a 083a 1519 08c0
   [ktlint]     00000e0: 0080 12fc 0303 1006 01b8 04b0 3609 1509
   [ktlint]     00000f0: 360a 150a 02a0 002f bb01 5559 bb00 5e59
   [ktlint]     0000100: b700 6213 0114 b600 6819 08b6 0068 1304
   [ktlint]     0000110: b2b6 0068 1304 b4b6 0068 b600 afb7 0158
   [ktlint]     0000120: c001 5abf 0015 0936 0b19 083a 0a03 360c
   [ktlint]     0000130: 190a 59c7 000e bb00 7959 1303 5bb7 007e
   [ktlint]     0000140: bf15 0c15 0bb6 04b8 5913 04ba b801 ee3a
   [ktlint]     0000150: 0919 083a 0c15 0b04 6036 0d19 0c59 c700
   [ktlint]     0000160: 0ebb 0079 5913 035b b700 7ebf 150d b604
   [ktlint]     0000170: bc59 1304 beb8 01ee 3a0a bb04 8559 1909
   [ktlint]     0000180: 1304 8919 0ab7 048e b604 9f00 3a16 1915
   [ktlint]     0000190: 1916 b900 bd02 0057 a7ff 2719 05c0 00bf
   [ktlint]     00001a0: 3a15 1911 1912 1913 1914 1915 c000 91b8
   [ktlint]     00001b0: 02df c000 91b2 04c0 b704 c34d b201 d699
   [ktlint]     00001c0: 000d 2cb2 04c8 c001 fdb6 04cc 2cb0     
   [ktlint]   Stackmap Table:
   [ktlint]     full_frame(@191,{Object[#2],Object[#225],Top,Object[#145],Object[#145],Object[#158],Object[#164],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Uninitialized[#31],Uninitialized[#31],Object[#225],Object[#158]},{})
   [ktlint]     full_frame(@292,{Object[#2],Object[#225],Top,Object[#145],Object[#145],Object[#158],Object[#164],Object[#4],Object[#137],Integer,Integer,Top,Top,Top,Top,Top,Top,Uninitialized[#31],Uninitialized[#31],Object[#225],Object[#158],Object[#158]},{})
   [ktlint]     full_frame(@321,{Object[#2],Object[#225],Top,Object[#145],Object[#145],Object[#158],Object[#164],Object[#4],Object[#137],Integer,Object[#137],Integer,Integer,Top,Top,Top,Top,Uninitialized[#31],Uninitialized[#31],Object[#225],Object[#158],Object[#158]},{Object[#137]})
   [ktlint]     full_frame(@364,{Object[#2],Object[#225],Top,Object[#145],Object[#145],Object[#158],Object[#164],Object[#4],Object[#137],Object[#137],Object[#137],Integer,Object[#137],Integer,Top,Top,Top,Uninitialized[#31],Uninitialized[#31],Object[#225],Object[#158],Object[#158]},{Object[#137]})
   [ktlint]     full_frame(@411,{Object[#2],Object[#225],Top,Object[#145],Object[#145],Object[#158],Object[#164],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Uninitialized[#31],Uninitialized[#31],Object[#225],Object[#158]},{})
   [ktlint]     full_frame(@460,{Object[#2],Object[#225],Object[#1153],Object[#145],Object[#145],Object[#158],Object[#164],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#1153],Object[#1153],Object[#225],Object[#158],Object[#191]},{})
   [ktlint] 
   [ktlint] 	at java.lang.Class.getDeclaredMethods0(Native Method)
   [ktlint] 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2688)
   [ktlint] 	at java.lang.Class.getMethod0(Class.java:2937)
   [ktlint] 	at java.lang.Class.getMethod(Class.java:1771)
   [ktlint] 	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)

**Comment by shyiko** [comment]
Hi @stalexxx.

I moved ~/.m2 (to make sure local Maven cache is not used) and tried ktlint through
```sh
$ ./mvnw --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)
Maven home: /home/shyiko/.m2/wrapper/dists/apache-maven-3.3.9-bin/5idsp2re5hobq3cp5qhqv0ru0h/apache-maven-3.3.9
Java version: 1.8.0_74, vendor: Oracle Corporation
Java home: /home/shyiko/.jabba/jdk/1.8.74/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.11-1-arch", arch: "amd64", family: "unix"
```
Everything seems to be in order.
My only guess is that Maven experienced some kind of error (like incomplete/interrupted artifact download) that brought you to that state. Nuke `~/.m2/repository/com/github/shyiko/ktlint` (or move whole ~/.m2 somewhere) and try again. 

Let me know if doesn't help.
Thank you.

**Comment by shyiko** [comment]
See also - https://github.com/sbt/sbt/issues/3516.
