### ISSUE TITLE
modifiers order

### ISSUE THREAD

**Issue by gmariotti** [shyiko/ktlint#146]
Ktlint formatting doesn't respect the suggested order for modifiers from [Kotlin Coding Conventions](https://kotlinlang.org/docs/reference/coding-conventions.html#modifiers). Specifically, instead of accepting the order `tailrec suspend fun`, it corrects it to `suspend tailrec fun`. Is this an expected behavior or something that will be updated?

**Comment by shyiko** [comment]
@gmariotti thank you for letting us know. https://github.com/shyiko/ktlint/blob/master/ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/ModifierOrderRule.kt#L38 will be fixed to match official recommendation as part of the next release.

**Comment by gmariotti** [comment]
@shyiko great, thanks!!

**Comment by shyiko** [comment]
Fixed in [0.16.0](https://github.com/shyiko/ktlint/releases/tag/0.16.0).
