### ISSUE TITLE
 Missing spacing after "}" conflict with "?"

### ISSUE THREAD

**Issue by dsvoronin** [shyiko/ktlint#15]
ktlint error:  Missing spacing after "}"

what ktlint expects: `find { it.default ?: false } ?.phone`
what idea reformat code do `find { it.default ?: false }?.phone`

idea reformat is right!

**Comment by shyiko** [comment]
Thank you! Fixed in 0.2.1 (it might take up to 2 hours for Maven Central sync to take place).
