### ISSUE TITLE
ktlint not compatible with kotlin 1.2.21

### ISSUE THREAD

**Issue by filipedelimabrito** [shyiko/ktlint#150]
When trying to use Ktlint with Kotlin 1.2.21 in an Android project, the following Gradle Build message is shown:

> Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/your_user/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.2.20/27671864206ef5bd946972619ed4ac4ae1397b2/kotlin-compiler-embeddable-1.2.20.jar
Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing org/jetbrains/kotlin/psi/KtImportsFactory.class
Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/your_user/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.2.20/27671864206ef5bd946972619ed4ac4ae1397b2/kotlin-compiler-embeddable-1.2.20.jar

**Comment by vanniktech** [comment]
Make sure you're running on the latest version. Dunno which one exactly fixed this. 0.15.0 should work for sure.

**Comment by fvermeulen** [comment]
It is maybe a bit old, but I think you have to clean your project and try it again.
We are using the latest kotlin-version as well without any problems :)

**Comment by shyiko** [comment]
@vanniktech @fvermeulen thank you :bowing_man:  
@filipedelimabrito let us know if you still have problems with getting ktlint to work. Otherwise this ticket is closed.

**Comment by filipedelimabrito** [comment]
I was happiness to install the Ktlint! The mistake was trying to insert the configuration inside the wrong `build.gradle` file. But I got an error when applying the java plugin (`apply plugin: "java"`). 

What do you think about [these suggestions](https://github.com/shyiko/ktlint/issues/172)?
