### ISSUE TITLE
Running format on functions with annotations above params reindents only the annotation

### ISSUE THREAD

**Issue by jeremymailen** [shyiko/ktlint#161]
If you take a source file with annotations above parameters like this:
```Kotlin
import org.jetbrains.annotations.Nullable

class Tester {

    fun annotated(@Nullable
                  param: String) {
        println("nullable $param")
    }
}
```
`ktlint -F Test.kt`
You'll get:
```Kotlin
import org.jetbrains.annotations.Nullable

class Tester {

    fun annotated(
        @Nullable
                  param: String
    ) {
        println("nullable $param")
    }
}

```
The workaround is that you can manually fix the indent of the param and `ktlint` will accept that too.

**Comment by shyiko** [comment]
Thank you, Jeremy. Fixed in [0.17.0](https://github.com/shyiko/ktlint/releases/tag/0.17.0) (Maven Central sync might take up to 25 minutes).
