### ISSUE TITLE
Why ktlint doesn't fails when auto-correct is enabled

### ISSUE THREAD

**Issue by tonilopezmr** [shyiko/ktlint#162]
When I run `ktlint -F` it doesn't fail when there is something that ktlint can't resolve it, only show error on the screen but doesn't return 1.

**Comment by shyiko** [comment]
Good catch! Fixed [0.17.0](https://github.com/shyiko/ktlint/releases/tag/0.17.0) (Maven Central sync might take up to 25 minutes).

**Comment by tonilopezmr** [comment]
Thank you! too fast!

**Comment by HannahFerch** [comment]
Hi, I have the same issue that was reported before the fix. When I run ktlint -F the commit passes even though there are reported formatting issues which cannot be auto corrected. I would like the commit to be failed in that case.

In the docs for ktlint -F it says: "auto-correct style violations (if some errors cannot be fixed automatically they will be printed to stderr)". Which doesn't mention that failing the commit is intended.

Is it possible to have the commit fail if there are issues which cannot be auto corrected?

Thanks!
