### ISSUE TITLE
Can not apply Java plugin

### ISSUE THREAD

**Issue by tarunattri** [shyiko/ktlint#170]
I am building a library project in kotlin. I wanted to use ktlint for code style violations. But following error is thrown as soon as we add(Which is first step in integration using gradle)
` apply plugin: "java"`

**Error:The 'java' plugin has been applied, but it is not compatible with the Android plugins.**

Other plugins that I am using are : 
`apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android-extensions'
`

Please let me know in case anything else is required in this from my side.

**Comment by shyiko** [comment]
Try removing `apply plugin: "java"`. 

If that doesn't help - take a look at 
[mozilla-mobile/focus-android](https://github.com/mozilla-mobile/focus-android/blob/master/build.gradle#L58), [mozilla-mobile/firefox-tv](https://github.com/mozilla-mobile/firefox-tv/blob/master/build.gradle#L50), [codebutler/farebot](https://github.com/codebutler/farebot/blob/0baeba894ff6a518fbb5212e67a0ea2ecc6afe04/build.gradle#L92), [wordpress-mobile/WordPress-FluxC-Android](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/build.gradle#L46) gradle configs.

And if that doesn't help either - try [one of Gradle plugins](https://github.com/shyiko/ktlint#with-a-plugin).

P.S. I'd be grateful if you could report back what was wrong / solution.

**Comment by tarunattri** [comment]
removing `apply plugin: "java"` solved the issue. I don't know when it is not needed , why it is mentioned in documentation. Anyway thanks for your prompt response in this.

**Comment by filipedelimabrito** [comment]
@shyiko Thanks for provide Ktlint installation on some projects. The mentioned error by @tarunattri also has occur with me, so I wrote some [suggestions](https://github.com/shyiko/ktlint/issues/172).
