### ISSUE TITLE
Improve Gradle installation.

### ISSUE THREAD

**Issue by filipedelimabrito** [shyiko/ktlint#172]
This is just a suggestion due to some troubles that the users is having when trying to integrate Ktlint via Gradle into their projects.

- Specify the root `build.gradle`: An Android project has at least two build.gradle file, so I think that is a nice idea to specify the gradle file to use Ktlint.

- Remove the `apply plugin: "java"`: First, it seems to be redundant the usage of the java plugin if we are using a Kotlin linter into a Kotlin project. Second it [doesn't seem to work](https://github.com/shyiko/ktlint/issues/170).

**Comment by shyiko** [comment]
Will do. Thank you, Filipe!

**Comment by shyiko** [comment]
README updated.
