### ISSUE TITLE
Is there an HTML reporter?

### ISSUE THREAD

**Issue by autonomousapps** [shyiko/ktlint#176]
It would be nice to see an HTML report generated. I'm not averse to writing one myself, but I thought I'd ask before reinventing the wheel. Thanks!

**Comment by shyiko** [comment]
Hi Tony.

The only html reporter I'm aware of is https://github.com/mcassiano/ktlint-html-reporter. There is a bug (in ktlint) preventing `ktlint --reporter=com.github.mcassiano:ktlint-html-reporter:master-SNAPSHOT` from working, however. I'll publish a new release with a bugfix within 24h.

If you end up writing your own reporter - let me know. I'll add a link to the README.

**Comment by shyiko** [comment]
`ktlint --reporter=html,artifact=com.github.mcassiano:ktlint-html-reporter:master-SNAPSHOT` fixed in [0.20.0](https://github.com/shyiko/ktlint/releases/tag/0.20.0).
