### ISSUE TITLE
Add way to install IntelliJ codestyle locally to project

### ISSUE THREAD

**Issue by chrisbanes** [shyiko/ktlint#178]
At the moment the `--apply-to-idea` parameter installs the codestyle globally to the IJ/AS profile, and changes the project to use that global profile.

I prefer to bundle the codestyle locally in the project's `.idea` folder ([example](https://github.com/chrisbanes/tivi/tree/master/.idea)). It would be nice if there was a nice way to do that. I'd even argue it should be the default (but we're probably past that now).

**Comment by shyiko** [comment]
Thank you for the example, Chris! 
If what we need can be configured through project's `.idea` then there is absolutely no reason to modify anything globally. I'll update `--apply-to-idea`.
:bowing_man:

**Comment by vanniktech** [comment]
I never commit those .idea folders and I'd use the current solution. I guess having both would not harm either way.

**Comment by shyiko** [comment]
Added `ktlint --apply-to-idea-project` ([0.22.0](https://github.com/shyiko/ktlint/releases/tag/0.22.0)+).
