### ISSUE TITLE
Android Studio 3.1 Kotlin Lint Checks vs ktlint

### ISSUE THREAD

**Issue by CraggyHaggy** [shyiko/ktlint#179]
In AndroidStudio 3.1 was added `Kotlin Lint Checks`. So will this library be supported after this new changes from Google team?

**Comment by shyiko** [comment]
Kotlin is not used for Android development only. Even if `Kotlin Lint Checks` were mutually exclusive with ktlint (which they are not) there are still other areas were Kotlin is (increasingly) used (server/client-side, Kotlin/Native). So, yes, ktlint remains supported. An addition of `Kotlin Lint Checks` in A/S changes nothing in this regard.
