### ISSUE TITLE
Add wiki info for building

### ISSUE THREAD

**Issue by Zehhu** [shyiko/ktlint#18]
Any chance on getting a small section on how to build ktlint from source?

Thanks!

**Comment by shyiko** [comment]
Sure. 

See https://github.com/shyiko/ktlint#development.

Basically all you need to do is:
```
git clone https://github.com/shyiko/ktlint && cd ktlint 
../mvnw -Pcapsule clean package -Dmaven.test.skip=true # should produce "./ktlint/target/ktlint"
```

**Comment by Zehhu** [comment]
Thanks!
