### ISSUE TITLE
Class type parameters declaration (indentation)

### ISSUE THREAD

**Issue by badoualy** [shyiko/ktlint#180]
I have the following class declaration
```kotlin
class BiAdapter<C : RecyclerView.ViewHolder, V1 : C, V2 : C, out A1, out A2>(
    val adapter1: A1,
    val adapter2: A2
) : RecyclerView.Adapter<C>()
    where A1 : RecyclerView.Adapter<V1>, A1 : ComposableAdapter.ViewTypeProvider,
          A2 : RecyclerView.Adapter<V2>, A2 : ComposableAdapter.ViewTypeProvider {
```

And I get an error while using `klintCheck`, because the last line has a 10 spaces indentation (to have `A2` aligned with `A1`, and it's done automatically be Intellij

Not sure what is the recommended format in this case, this format feels the most natural, I guess

```kotlin
) : RecyclerView.Adapter<C>() where
A1 : RecyclerView.Adapter<V1>, A1 : ComposableAdapter.ViewTypeProvider,
A2 : RecyclerView.Adapter<V2>, A2 : ComposableAdapter.ViewTypeProvider {
```

would fix the error, but I'm not sure it's the recommended format.

I remember reading an issue in some github about code style for kotlin, where basically no one would agree on a standard format.

What's the recommendation for this in Klint?

**Comment by shyiko** [comment]
Hi @badoualy.
Thank for you the ticket.

It looks like vertical alignment is a way to go in this case (https://kotlinlang.org/docs/reference/generics.html#upper-bounds). I'll disable indent check inside `where` clause for now. We'll revisit it as part of (long-overdue) indent rule overhaul.
