### ISSUE TITLE
Allow to replace existing rules?

### ISSUE THREAD

**Issue by AleksandrSl** [shyiko/ktlint#181]
I've read #21, but still I don't see why some rules (e.g. indent size) can be configured, and other rules cannot. 
e.g. there is no way to use 2 lines to separate imports from class definition. Standard rules are cool, but a little bit more configuration options would be great.

**Comment by adelnizamutdinov** [comment]
Yes! for example, the rationale behind

> No newline before `&&`

is unclear. We can tune the continuation intent size, why not also be able to tune the position of `&&` and `||`?

**Comment by AleksandrSl** [comment]
Closed, since it seems to be resolved partially by [this](https://github.com/arturbosch/detekt/pull/855)
