### ISSUE TITLE
Introduce public api for "calculateLineColByOffset" and SegmentTree 

### ISSUE THREAD

**Issue by arturbosch** [shyiko/ktlint#186]
We are currently adopting KtLint as an api for detekt.
It works great and makes all KtLint rules configurable through the detekt api.

One problem I have is converting the offsets from line numbers which can throw exceptions when using DiagnosticUtils on AstNodes. 
I see that you have written your own functionality like "positionByOffset" [here](https://github.com/shyiko/ktlint/blob/4e58236e9a03a15a8fa2455298faa4a07a2cbcf0/ktlint-core/src/main/kotlin/com/github/shyiko/ktlint/core/KtLint.kt#L306).

Do you mind making it a public api in the ktlint-core module? That would really help and reduce cloning of your code :)

**Comment by shyiko** [comment]
Hi Artur.
I'd rather avoid exposing anything that is not strictly ktlint-related (less "surface area" to keep backward-compatible). Take whatever you need and don't bother with attribution. It's less than 50 lines of code after all :)
