### ISSUE TITLE
chain-wrapping auto fix can incorrectly comment out operator

### ISSUE THREAD

**Issue by eventualbuddha** [shyiko/ktlint#192]
Here's a minimal example:

```kt
// example.kt
fun and(a: Boolean, b: Boolean): Boolean {
    return (a //
        && b)
}
```

When running `ktlint --format` on the file above, it reformats it to this:

```kt
// example.kt
fun and(a: Boolean, b: Boolean): Boolean {
    return (a // &&
        b)
}
```

This clearly introduces a syntax error due to the operator now being inside the line comment. I'd expect `ktlint` to move the operator before the line comment like so:

```kt
// example.kt
fun and(a: Boolean, b: Boolean): Boolean {
    return (a && //
        b)
}
```

There's another similar problem in this example:

```kt
// example2.kt
fun and(a: Boolean, b: Boolean): Boolean {
    return (a
        //
        && b)
}
```

Which becomes this:

```kt
// example2.kt
fun and(a: Boolean, b: Boolean): Boolean {
    return (a
        // &&
        b)
}
```

**Comment by shyiko** [comment]
Fixed in [0.22.0](https://github.com/shyiko/ktlint/releases/tag/0.22.0).
