### ISSUE TITLE
Match indent to continuation indent?

### ISSUE THREAD

**Issue by ScottPierce** [shyiko/ktlint#196]
The documentation for the most recent version currently states:
> change Continuation indent to the same value as Indent (4 by default).

Isn't this against the Kotlin and Android style guides? Both style guides have / use continuation indents currently, and the continuation indents are expected to be double the normal indent (defaulting to 8). In order to compensate, many things that would normally use continuation indents, no longer use continuation indents. i.e. constructor properties, or method chaining:

```kotlin
data class Example(
    val a: String, // <-- normal indent, not continuation indent
    val b: String
)
```

The solution of making the continuation indent to match the normal indent seems wrong. Instead, ktlint needs to be updated to stop expecting continuation indents in locations where the style guide prohibits them.

**Comment by igorwojda** [comment]
I kind of like this change, but I think it's just a matter of personal preference.

Whatever team decides I want to point out that `ktlint --apply-to-idea-project --android ` does not set `continuation indent` to `4`, so this must be set manually (currently official ktlint settings are conflicting with Android Studio formatting settings)

**Comment by shyiko** [comment]
1. `continuation_indent_size=4` was the default in ktlint pretty much from the beginning.  
At some point it was changed to match Android Style Guide's "8" (note that official [Kotlin Style Guide](https://kotlinlang.org/docs/reference/coding-conventions.html) doesn't say a thing about continuation indent, it never did) but was swiftly reverted back to 4 after `continuation indent` was replaced with `indent` in most of the cases (constructor/method parameters, method chaining) (simply to avoid all the back and forth). 
2. In general, 4 as a default is not as important as you might think:  
(at least not while [ident rule is dumb](https://github.com/shyiko/ktlint/issues/141))
- ktlint obeys value specified in .editorconfig. e.g. if `continuation_indent_size=8` - `ktlint --apply-to-idea-project` will set "8" as continuation indent.
- if you upgrade from ktlint@0.1.0 all the way up to the latest ktlint@0.22.0, unless you had a custom (and by custom I mean anything but `continuation_indent_size=4` & `continuation_indent_size=8`) you shouldn't notice a thing (as far as indent rule goes). 
- no matter what you have in .editorconfig the following is true:
	- constructor/method parameters are expected to be "single-indent"ed
	- everything else is _at least_ "single-indent"ed

  (as a direct result if you run ktlint against any codebase without `continuation_indent_size` in .editorconfig no errors will be printed regardless of whether the code is using single or double-indent)
3. https://github.com/shyiko/ktlint/issues/120 is still open. 4 vs 8 default is by no means resolved.
4. If Kotlin Style Guide enumerates all the cases where continuation_indent must be used (which I really hope they find the wisdom not to do as continuation indent brings zero value and only complicates the style guide) ktlint **will be** updated to match that recommendation.

**Comment by shyiko** [comment]
Thanks @igorwojda. I'll look into it.

**Comment by shyiko** [comment]
Closing in favor of https://github.com/shyiko/ktlint/issues/120.

@igorwojda it seems like `ktlint --apply-to-idea-project` changes continuation indent to match the indent after all (tested on latest Android Studio). Feel free to open a separate ticket if that's not what you observe. Thank you.
