### ISSUE TITLE
Install ktlint with homebrew?

### ISSUE THREAD

**Issue by joshfriend** [shyiko/ktlint#2]
I'm setting this up on a build server running OSX and having homebrew installation available would be awesome.

**Comment by shyiko** [comment]
Hi Josh. Absolutely. If you already have formula lying around then I'll be happy to accept the PR. If not - I'll do after work.

**Comment by shyiko** [comment]
@joshfriend Done. See readme.md.

**Comment by joshfriend** [comment]
Fantastic, thank you!
