### ISSUE TITLE
Simplify code-gen tooling use-case 

### ISSUE THREAD

**Issue by hsyed** [shyiko/ktlint#203]
I am working on a stub generator for GRPC and would like to use ktlint to just do a simple format of the code.

[Google java format](https://github.com/google/google-java-format) has a simple 3 liner for usage in code gen tooling.

I'm having to read through the code to figure out how to do the same.This is where I am at with trying to figure out what I need to plug into the third param to get the formatting to occur ;)

```
     val content = applyTemplate("common/grpc/gen/protoc-gen-grpc-kotlin/templates/KtStub.mustache", context).let {
            KtLint.format(
                it,
                listOf(StandardRuleSetProvider().get()),
                { _, _ ->}
            )
        }
```

A utility method for vanilla code formatting or an example in the readme would be very helpful.

**Comment by shyiko** [comment]
Will be done in #340. 🙇
