### ISSUE TITLE
ParametersOnSeparateLinesRule can't be handled by Intellij IDEA

### ISSUE THREAD

**Issue by Jacksgong** [shyiko/ktlint#206]
Hello, thanks for your nice job. We are using this project to the check style issue of kotlin on our project.

But there is one thing is not make sense:

#### 1. Effect checkstyle rule for IDEA

I have already run the command `ktlint --apply-to-idea-project --android ` on my project root directory, and see it really effect after I restart my Android Studio

![image](https://user-images.githubusercontent.com/6176417/39617246-85db2fb6-4fb1-11e8-8dbc-2e5323dc0a52.png)

#### 2. Format kotlint file by IDEA BUT PROBLEM EXIST

I format the `TestDarwinActivity.kt` file through Android Studio, but  after the format the problem of `Parameter should be on a separate line (unless all parameters can fit a single line)` is still exist

![image](https://user-images.githubusercontent.com/6176417/39617396-25c159e2-4fb2-11e8-8acf-39d5b4534e29.png)

#### 3. Can't find any solution for this problem

I check the kotlint code style setting can't find anywhere to solve this ParametersOnSeparateLinesRule for the IDEA formatter

![image](https://user-images.githubusercontent.com/6176417/39617454-62394268-4fb2-11e8-9edd-e5793bf293f4.png)

---

So could you please have any suggestions to handle ParametersOnSeparateLinesRule by the Intellij IDEA

---

Finally, I think the problem is it allows parameters on one line but it not allowed by ktlint

**Comment by shyiko** [comment]
Hey @Jacksgong. 

Any chance you can attach TestDarwinActivity.kt? 

Normally, Ctrl+Alt+L should do the job. When Intellij built-in formatter is unable to produce expected result you can either `ktlint -F` (same as `ktlint --format`) or do it manually with Alt+Enter -> `Put parameters on separate lines`:

![img-2018-05-04-112908](https://user-images.githubusercontent.com/370176/39645888-977f9d10-4f8e-11e8-9ddb-b963d0221d70.png)

**Comment by Jacksgong** [comment]
Thank you so much, the way of `Alt + Enter` to do this job manually is work for me(on Mac is `Option + Enter`).

**Comment by ronie-athaydes-ifood** [comment]
Any chance of providing support for this rule through `ktlint -F` or IDEA formatter instead doing it mannualy?
