### ISSUE TITLE
Execution failed for task ':app:ktlintDebugAndroidTestFormat'.

### ISSUE THREAD

**Issue by iAmMONK** [shyiko/ktlint#210]
Hi, I am getting the same error on both tasks.(Format and Check)

Execution failed for task ':app:ktlintDebugAndroidTestFormat'.
> Process 'command 'C:\Program Files\Java\jdk-10.0.1\bin\java.exe'' finished wit
h non-zero exit value 1

It use to work on first run(showed some code errors but then BUILD FAILED). I Fixed the code, and next run I didn't get any bugs found. Turned back the code with bugs and got no bugs found.

What I tried:
Reinstall Java(versions 8 and 10)
Enabled multiDex
Executing ./gradlew app:ktlintCheck, ./gradlew ktlintCheck, ./gradlew clean
Tried to Clean project from IDE and then rebuild it.

**Comment by iAmMONK** [comment]
Ok guys, magic happens, went to eat something and now it works. I'm still getting the error but now it shows the mistakes at least.

Have to check now if I'm home alone...

**Comment by shyiko** [comment]
Sorry for taking so long to respond. Let me know if you still having this problem. Otherwise this ticket is closed.
