### ISSUE TITLE
Covert tabs to spaces

### ISSUE THREAD

**Issue by klesniewski** [shyiko/ktlint#214]
We are currently using tabs for indentation, but we would like to go with standard Kotlin code style convention. That means we have many files across many projects, in which we need to convert tabs to spaces. I would expect `format` to be able to cope with the task, but unfortunately it yields errors as follows:

```
Format could not fix > src\main\kotlin\some\package\SomeClass.kt:45:1: Unexpected indentation (1) (it should be 4)
``` 

Could KtLint just convert each tab character to 4 spaces (or whatever is configured)?

KtLint version: 0.23.1

**Comment by shyiko** [comment]
Hi. 

This is not (yet) supported, unfortunately. In the meantime, [expand](https://linux.die.net/man/1/expand) should do the job:

```sh
find src/ -name '*.kt' | xargs -L1 -I{} sh -c 'expand -i -t4 {} > {}~; mv -f {}~ {}'
```

**Comment by klesniewski** [comment]
Thanks @shyiko for going the extra mile and proposing alternative.

Should I leave the issue open or should I close it?

**Comment by shyiko** [comment]
Let's keep it open (just in case I forget to fix this as part of https://github.com/shyiko/ktlint/issues/141)

**Comment by shyiko** [comment]
Added in [0.25.0](https://github.com/shyiko/ktlint/blob/master/CHANGELOG.md#0250---2018-07-25).
