### ISSUE TITLE
Can I enable wildcard import

### ISSUE THREAD

**Issue by CoXier** [shyiko/ktlint#217]
AS automatically enable wildcard import in my team, so can I enable wildcard import in `ktlint`?

**Comment by shyiko** [comment]
[Nope](https://github.com/shyiko/ktlint/issues/48#issuecomment-380873767). Sorry.

**Comment by zackees** [comment]
We should be treated like adults and not have this rule enforced on us. The big significant downside is that the STOCK ANDROID IDE AUTO IMPORTS.

This is just another foot gun to using a tool. Users are reporting an issue and the creators just thumb their nose and make us do painful work arounds. We could just allow the rule and move on with our lives instead we have to spend time arguing over the obvious.
