### ISSUE TITLE
Space between parentheses does not trigger a warning

### ISSUE THREAD

**Issue by vanniktech** [shyiko/ktlint#223]
I'd expect `fun test( ) = Unit` to be triggered since the space between the parentheses is not necessary. Also when using the autoformatting feature it should be transformed into `fun test() = Unit`.

**Comment by shyiko** [comment]
Fixed in [0.24.0](https://github.com/shyiko/ktlint/blob/master/CHANGELOG.md#0240---2018-06-22).
