### ISSUE TITLE
When wrapping chained calls "." character / "?." operator should be placed on the next line

### ISSUE THREAD

**Issue by shyiko** [shyiko/ktlint#23]
https://github.com/yole/kotlin-style-guide/issues/9

**Comment by shyiko** [comment]
Added in 429fe26ac1d7734f90a9d594546a35908a1d81de.

**Comment by binkley** [comment]
Hi, I'm struggling to disable this rule.  I've tried `chain_wrapping = false` and `chain-wrapping = false` in `.editorconfig` to no avail.  Do you have suggestions?
