### ISSUE TITLE
typealias X should be declared in a file named X.kt not reported by IntelliJ but reported by ktlint

### ISSUE THREAD

**Issue by timolehto** [shyiko/ktlint#230]
Hi,

If I add one type alias in a file `X.kt` IJ does not complain about them, but running `ktlint` on the console does complain that they should be defined in separate file. Also another interesting thing is that using `kotlinter-gradlew` and running `./gradlew lintKotlinMain` it too does not complain. What could be causing this mismatch in the rules? kotlinter version 1.12.0 should be using the lates 0.23.1 version of ktlint which is also the version brew installed too.

**Comment by timolehto** [comment]
The `kotlinger-gradlew` side is now fixed and also runs FilenameRules as expected, but IntelliJ doesn't care so keeping this one still open.

**Comment by shyiko** [comment]
ktlint has plenty of rules that are not available in IntelliJ. We're not trying to re-implement IntelliJ Inspections.  

Having said that, if a file contains a single typealias and the name of the file does not match the typealias then a lint error is expected (provided a file is not named `package.kt`). This check can be disabled as described in https://github.com/shyiko/ktlint/issues/237#issuecomment-399641580.

**Comment by timolehto** [comment]
Oh yeah, now that I reread the readme I realise that "formatter producing 100% ktlint-compatible code" obviously does not mean that IJ would flag 100% of ktlint errors/warnings.
