### ISSUE TITLE
Check package name

### ISSUE THREAD

**Issue by thauk-copperleaf** [shyiko/ktlint#238]
IntelliJ has an inspector setting to detect when the package name does not match the containing directory for the file.

Does ktlint have such an optional rule, and if so, what is its name?

**Comment by shyiko** [comment]
Right now, only [filename is checked](https://github.com/shyiko/ktlint/blob/master/ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/FilenameRule.kt). It should be fairly easy to implement, though.

**Comment by shyiko** [comment]
Added in [0.25.0](https://github.com/shyiko/ktlint/blob/master/CHANGELOG.md#0250---2018-07-25) (thanks, @yokotaso!).
