### ISSUE TITLE
I get Error "finished with non-zero exit value 1", at  ktlintFormat

### ISSUE THREAD

**Issue by frankswu** [shyiko/ktlint#244]
> Task :ktlintFormat FAILED
/Users/frankswu/Documents/workspace/android/give/app/src/main/java/com/guanaitong/home/activity/AllAppActivity.kt:29:1: Wildcard import
/Users/frankswu/Documents/workspace/android/give/app/src/main/java/com/guanaitong/home/adapter/AllAppAllAdapter.kt:24:1: Wildcard import
/Users/frankswu/Documents/workspace/android/give/app/src/main/java/com/guanaitong/home/adapter/AllAppTabAdapter.kt:14:1: Wildcard import
/Users/frankswu/Documents/workspace/android/give/app/src/main/java/com/guanaitong/home/fragment/HomeFragment.kt:36:1: Wildcard import
/Users/frankswu/Documents/workspace/android/give/app/src/main/java/com/guanaitong/home/fragment/HomeFragment.kt:38:1: Wildcard import
/Users/frankswu/Documents/workspace/android/give/app/src/main/java/com/guanaitong/home/presenter/AppHomePresenter.kt:6:1: Wildcard import
/Users/frankswu/Documents/workspace/android/give/app/src/main/java/com/guanaitong/home/presenter/AppHomePresenter.kt:8:1: Wildcard import

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ktlintFormat'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by shyiko** [comment]
If you upgrade ktlint to 0.24.0 you'll see `Wildcard import (cannot be auto-corrected)`. Android Studio/IDEA's "Optimize Imports..." can take care of it (provided [Use single name import](https://github.com/shyiko/ktlint#-with-intellij-idea) is on).
