### ISSUE TITLE
Learning the API

### ISSUE THREAD

**Issue by lwasyl** [shyiko/ktlint#261]
Hi, 

I'd like to start working on ktlint a bit, write some custom rules etc., however the API (`org.jetbrains.kotlin.*`, `com.intellij.lang.*` and `com.intellij.psi.`) are a bit obscure. This might not be the place to ask, but since KtLint directly exposes these APIs, what are some good sources to learn about what is what here, what to use when, how to discover necessary classes etc.?

Thanks

**Comment by shyiko** [comment]
Hi Łukasz.

There is very little documentation, unfortunately. Most of the time you'll have to dig into the sources - [org.jetbrains.kotlin.*](https://github.com/JetBrains/kotlin/tree/1.2.60/compiler/psi/src/org/jetbrains/kotlin), [com.intellij.*](https://github.com/JetBrains/intellij-community/tree/master/platform/core-api/src/com/intellij) ([org.jetbrains.kotlin.psi.psiUtils.*](https://github.com/JetBrains/kotlin/blob/1.2.60/compiler/psi/src/org/jetbrains/kotlin/psi/psiUtil/psiUtils.kt) and [com.intellij.psi.util.PsiTreeUtil](https://github.com/JetBrains/intellij-community/blob/master/platform/core-api/src/com/intellij/psi/util/PsiTreeUtil.java) proved to be particularly useful). 

My personal recommendation would be start with [ktlint --print-ast --color path/to/file.kt](https://github.com/shyiko/ktlint#ast). It should give an idea about how the AST is structured, classes & types involved.

(most built-in rules are [here](https://github.com/shyiko/ktlint/tree/master/ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard))
