### ISSUE TITLE
Parameter should be on a separate line 

### ISSUE THREAD

**Issue by lujiwen** [shyiko/ktlint#265]
ktlint would throw waning like

Parameter should be on a separate line 

on the first line of `class declaration data class UserRto(val lastName : String = ""`,
I know the style of the above code is [acceptable](https://ktlint.github.io/), but how can I mute this warning? Would you please kindly help me with this, thanks in advance!

**Comment by lujiwen** [comment]
![image](https://user-images.githubusercontent.com/3608828/43507510-ee540fac-959f-11e8-97cf-fd757b9ee3ef.png)
this is not ok! they will receive ktlint errors, but I want to keep the style and mute warnings like  'Parameter should be on a separate line' , how can I do that?

**Comment by shyiko** [comment]
ktlint.github.io needs to be updated (will be done as part of https://github.com/shyiko/ktlint/issues/115). 
Vertical alignment after "(" without a separating newline is no longer allowed. 
https://kotlinlang.org/docs/reference/coding-conventions.html#class-header-formatting / https://android.github.io/kotlin-guides/style.html#functions.
