### ISSUE TITLE
Exit code is non-zero when --format finds uncorrectable problems

### ISSUE THREAD

**Issue by hooper** [shyiko/ktlint#268]
This makes "ktlint --format" dissimilar to most automated code formatters, which have exit code 0 when the formatted code was successfully written back to the file/stdout. It would be easier to integrate ktlint with other systems as a code formatter if it returned 0 in this case (whether the errors are printed to stderr or not).

**Comment by shyiko** [comment]
It really depends on the tool. 
ktlint happens to behave identical to [standardjs](http://standardjs.com) (in terms of exit codes):
```sh
$ cat index.js
var x = ''
console.log("")

$ standard index.js
standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  /tmp/index.js:1:5: 'x' is assigned a value but never used.
  /tmp/index.js:2:13: Strings must use singlequote.
(exit code: 1)

$ standard --fix index.js
standard: Use JavaScript Standard Style (https://standardjs.com)
  /tmp/index.js:1:5: 'x' is assigned a value but never used.
(exit code: 1)
```

If you don't care about the exit code you can always `ktlint ... || true` (command line) / `failonerror="false"` (Maven) / `ignoreExitValue=true` (Gradle).
That being said, I am open to a PR that would introduce a flag (e.g. -z) forcing 0 exit code.
