### ISSUE TITLE
Crash on lambda

### ISSUE THREAD

**Issue by nicolaiparlog** [shyiko/ktlint#274]
When executing ktlint with Maven Ant Runner on this snippet...

```kotlin
fun loadGreetings(): List<Greeting> {
    return jdbc
        .query("SELECT phrase, audience FROM greeting_v1;")
        { rs, _ -> Greeting(rs.getString(1), rs.getString(2)) }
}
```

... ktlint seems to crash and return exit code `1`:

> [ERROR] -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException:
>     Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (ktlint)
>     on project coursefx: An Ant BuildException has occured: Java returned: 1

If I slightly reformat, ktlint works fine:

```kotlin
fun loadGreetings(): List<Greeting> {
    return jdbc.query(
        "SELECT phrase, audience FROM greeting_v1;"
    ) { rs, _ -> Greeting(rs.getString(1), rs.getString(2)) }
}
```

**Comment by shyiko** [comment]
Hey @nicolaiparlog. 

The first snippet is tripping over `curly-spacing` rule (which is expected):
```sh
$ ktlint _.kts 
/tmp/_.kts:4:9: Unexpected newline before "{"
(exit code: 1)

$ ./mvnw antrun:run@ktlint
<omitted>
[INFO] --- maven-antrun-plugin:1.8:run (ktlint) @ pom ---
[INFO] Executing tasks

ktlint:
   [ktlint] /tmp/_.kts:4:9: Unexpected newline before "{"
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
<omitted>
(exit code: 1)
```
Let me know if this does not solve your issue.

**Comment by nicolaiparlog** [comment]
Argh, the output clearly says _Unexpected newline before "{"_ - did I miss that the first time around? I was sure, this was no intentional exit, but now I can not reproduce that. Sorry for the triviality. 😕

**Comment by shyiko** [comment]
No worries!
