### ISSUE TITLE
Common root package

### ISSUE THREAD

**Issue by mhlz** [shyiko/ktlint#280]
Currently ktlint flags package names as invalid, if you're following the recommendation outlined in [the coding conventions](https://kotlinlang.org/docs/reference/coding-conventions.html#source-code-organization):

> In pure Kotlin projects, the recommended directory structure is to follow the package structure with the common root package omitted (e.g. if all the code in the project is in the "org.example.kotlin" package and its subpackages, files with the "org.example.kotlin" package should be placed directly under the source root, and files in "org.example.kotlin.foo.bar" should be in the "foo/bar" subdirectory of the source root).

I'd like for ktlint to be able to support this directory structure as it cuts down on the nesting a lot. IntelliJ does not generate warnings (anymore) either, when following this recommendation.

**Comment by shyiko** [comment]
Hi @mhlz. This was supposedly fixed in [0.28.0](https://github.com/shyiko/ktlint/blob/master/CHANGELOG.md#changed). Let me know if that's not the case (steps to reproduce would be great).

**Comment by mhlz** [comment]
You can test it in this project: https://github.com/mhlz/kotlin-issue

Either run ktlint from the command line or run mvn install. ktlint fails with

    ktlint:
       [ktlint] /Users/mhlz/Documents/IdeaProjects/acomodeo/kotlin-issue/src/main/kotlin/Main.kt:1:1: Package directive doesn't match file location (cannot be auto-corrected)
       [ktlint] /Users/mhlz/Documents/IdeaProjects/acomodeo/kotlin-issue/src/main/kotlin/model/TestClass.kt:1:1: Package directive doesn't match file location (cannot be auto-corrected)

**Comment by shyiko** [comment]
I see... Thank you, @mhlz. Reopening...

**Comment by serebit** [comment]
I have this issue as well with https://gitlab.com/serebit/diskord. Using the `kotlinter` gradle plugin, latest version

**Comment by mhlz** [comment]
So, I looked into fixing this myself, but it seems kinda difficult to do with the way that rules currently work. We'd need some sort of "module" wide state to determine the root package. Otherwise it's going to be hard to support all use cases. Maybe as a quick fix, it'd be good to disable this rule again? I'd like to keep following and recommending the JetBrains coding conventions, but with ktlint going against them it's kinda hard.

**Comment by shyiko** [comment]
@mhlz Disabled in [0.29.0](https://github.com/shyiko/ktlint/blob/master/CHANGELOG.md#0290---2018-10-02).
