### ISSUE TITLE
Issue error when there is unnecessary space around dot 

### ISSUE THREAD

**Issue by hmhagberg** [shyiko/ktlint#288]
For example, both lines below are fine according to ktlint 0.27

    fun String . foo() = "foo"
    " " . foo()

I would expect there to be an error, with the correct form being

    fun String.foo() = "foo"
    " ".foo()

**Comment by shyiko** [comment]
Thanks. Apparently we need something similar to [SpacingAroundCommaRule](https://github.com/shyiko/ktlint/blob/master/ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/SpacingAroundCommaRule.kt).

**Comment by AleksandrSl** [comment]
Can I take this one?

**Comment by AleksandrSl** [comment]
#293

**Comment by cable729** [comment]
This should be closed

**Comment by shyiko** [comment]
Indeed. Thank you.
