### ISSUE TITLE
Is there a visitor for XML attributes?

### ISSUE THREAD

**Issue by egek92** [shyiko/ktlint#290]
In our project we want developers to use only our custom view attributes with prefix `"ABC"`, that's why I want to write a custom rule to check layouts, and if it detects any attribute like `<Button>` instead of `<com.example.ABCButton>` I want to warn the developer. Is it possible to do this?

**Comment by shyiko** [comment]
Sorry but this is out of scope. ktlint deals with `*.kt`/`*.kts` only.
