### ISSUE TITLE
"Missing space after //" and IntelliJ IDEA

### ISSUE THREAD

**Issue by thauk-copperleaf** [shyiko/ktlint#298]
When commenting out a line in IntelliJ IDEA -- made by JetBrains, who of course also makes Kotlin -- a space is not added after the `//`. This is frustrating because ktlint requires this by default. So every time I comment out a block of lines, I have to tediously add extra spaces. And when uncommenting a line, the extra space is not removed.

Could this considered a bug in IntelliJ (because they don't agree with a specification regarding comment format) or an overly-strong rule in ktlint (because no such spec exists)?

**Comment by shyiko** [comment]
Space after // enforced in https://github.com/shyiko/ktlint/commit/cd3cfc866845a5a95e096be7bce86865c66df575. 
That being said, ability to disable rules on per-file basis is coming in #208.

**Comment by vincent-paing** [comment]
What's the name of this rule to disable it?

**Comment by Tapchicoma** [comment]
Name is "comment-spacing".
