### ISSUE TITLE
0.4.0 depends on upstream Kotlin 1.1 M04, which no longer available in Maven Central

### ISSUE THREAD

**Issue by orospakr** [shyiko/ktlint#31]
```
> Could not resolve all dependencies for configuration ':ktlint'.
   > Could not find org.jetbrains.kotlin:kotlin-compiler-embeddable:1.1-M04.
     Searched in the following locations:
         http://dl.bintray.com/populov/maven/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.1-M04/kotlin-compiler-embeddable-1.1-M04.pom
         http://dl.bintray.com/populov/maven/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.1-M04/kotlin-compiler-embeddable-1.1-M04.jar
         https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.1-M04/kotlin-compiler-embeddable-1.1-M04.pom
         https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.1-M04/kotlin-compiler-embeddable-1.1-M04.jar
     Required by:
         :joist-android:unspecified > com.github.shyiko:ktlint:0.4.0 > com.github.shyiko.ktlint:ktlint-core:0.4.0
```

**Comment by orospakr** [comment]
afaict it is standard for so-called 'beta' releases to have limited lifetimes on repositories in the Java world.

**Comment by shyiko** [comment]
Hi @orospakr. Thanks for letting me know. M04 is still available, the problem is Gradle ignores `<repositories>...</repositories>` (https://issues.gradle.org/browse/GRADLE-611). The easiest way to get it all working again is to add "maven { url "http://dl.bintray.com/kotlin/kotlin-eap-1.1" }" repository in your build.gradle. I'll update the readme.md in a minute.

**Comment by shyiko** [comment]
btw, if you don't need koltin 1.1 features you can go with the previous ktlint@0.3.1 release (in case you don't want to add EAP repo). feature-wise ktlint@0.4.0 and 0.3.1 are the same. The only difference is kotlin compiler version.

**Comment by orospakr** [comment]
Thank you for the great answers :)

**Comment by REggar** [comment]
@shyiko Can we have a release now with the requirement for `maven { url "http://dl.bintray.com/kotlin/kotlin-eap-1.1" }` now that 1.1.0 is out?

**Comment by shyiko** [comment]
@REggar done - [0.6.0](https://github.com/shyiko/ktlint/blob/master/changelog.md#060---2017-03-01).
