### ISSUE TITLE
Allow Unit in .editorconfig

### ISSUE THREAD

**Issue by gmariotti** [shyiko/ktlint#313]
Hi, looking at the [Jetbrains coding conventions](https://kotlinlang.org/docs/reference/coding-conventions.html#coding-conventions-for-libraries), for libraries is suggested to always explicitly specify the return type of a function, even if it's `Unit`. However, as far as I know, ktlint doesn't allow to disable the check on useless `Unit` globably. Do you think it make sense to have it as an option i the `.editorconfig` file? And if not, what would be your suggestion to disable the `Unit` check globably for a library project?

**Comment by vietj** [comment]
does ktlint fails or warns ?

the idea of ktlint in the generated code, is to reformat the code to be more kotlin-ish.

**Comment by gmariotti** [comment]
ktlint can do both, the only problem is that it will remove `Unit` from the return type of all the generated methods unless you disable the rule for the file.

**Comment by shyiko** [comment]
Ability to disable rules on per-file basis is coming in #208.

**Comment by gmariotti** [comment]
That's great news, thanks @shyiko!!
