### ISSUE TITLE
How well is Android kotlin style guide intergrated?

### ISSUE THREAD

**Issue by ursusursus** [shyiko/ktlint#325]
I tried your tool, and there are some thing that pass even though they should not according to android kotlin style guide

namely, "if" formatting, which says you shouldnt use brace-less ifs on multiple lines - ktlint allows this
and, vertical white space - last element of a class can have empty line after it - ktlint forbids that

**Comment by shyiko** [comment]
See https://github.com/shyiko/ktlint/issues/4#issuecomment-352208044. There are also a bunch of issues, like https://github.com/shyiko/ktlint/issues/174 that need to be resolved.
