### ISSUE TITLE
'Missing newline before ")"' in long function names

### ISSUE THREAD

**Issue by jlmd** [shyiko/ktlint#327]
In ktlint version 0.29.0, there is an issue when a function name is too long. It's not common in normal functions, but it's when writing test functions using spaces. Example:
```kotlin
fun `any long function with more than 120 chars should only break 'Exceeded max line length (120)' and not any other rule`() {
   ...
}
```
When analyzing the code with ktlint, it says there are two broken rules:
`Unexpected spacing after "("`
`Exceeded max line length (120)`

In this case, the only broken rule should be `Exceeded max line length (120)`, since adding a line break after the parenthesis when there are no parameters I think it does not make sense.

It was not happening in previous versions.

**Comment by shyiko** [comment]
Fixed in [0.30.0](https://github.com/shyiko/ktlint/blob/master/CHANGELOG.md#0300---2019-02-03).
