### ISSUE TITLE
LONG_STRING_TEMPLATE_ENTRY error with Kotlin 1.3.20

### ISSUE THREAD

**Issue by kenyee** [shyiko/ktlint#330]
Running lintKotlin with the latest 1.3.20 version of Kotlin seems to fail with this cryptic error:

```
Execution failed for task ':app-base:lintKotlinMain'.
> LONG_STRING_TEMPLATE_ENTRY
```

1.3.11 works fine.

**Comment by JakeWharton** [comment]
Dupe of #321.

**Comment by kenyee** [comment]
Definitely same issue..missed that EAP one because I thought it was older :-(
