### ISSUE TITLE
PROJECT STATUS UPDATE

### ISSUE THREAD

**Issue by shyiko** [shyiko/ktlint#337]
Hey everyone,

It's been more than a year since I **really** had the time to work on ktlint. I was hoping to "get back into the saddle" on multiple occasions but it doesn't look like things are going to change (especially considering that I don't do Kotlin/Java for a living anymore; most of the code I've written in the last year was either in Go or Rust). 

With that being said, I'm stepping down from ktlint development. 

I'm looking for a few folks (that have the time and dedication) to take over project.
If you're interested - shoot me an email or comment below. 

Over the next week or so I'll be moving/forking ktlint to [ktlint](https://github.com/ktlint) org.
Whoever decides to take ownership will get full access to that org and all the projects within.

I'm truly grateful to everyone who contributed to the project: @jlleitschuh @jeremymailen @jelloranger @yokotaso @ilya-gh @mydogtom @charbgr @cable729 @arturbosch @shiraji @bethcutler @locitao @kunny @mapyo @rom4ek @samcarlberg @miga9 @shashachu-pinterest @aleksandrsl @tapchicoma @tasugi @h-3-0 @vanniktech @ntsim @liutikas @twaddington @amincheloh @reggar + many more. Thank you all! 

♥,
Stan.

cc @jbarr21 @zacsweers @tyvsmith @0legg

**Comment by twaddington** [comment]
I'd love to help out in some capacity but am not sure I have the bandwidth to completely take over the project.

**Comment by shashachu-pinterest** [comment]
Hey Stan, I sent you an email. I also wanted to echo what @twaddington said - thanks for all the hard work!

**Comment by JLLeitschuh** [comment]
2 things.

1. I'm happy to take over, and I also trust @Tapchicoma.
2. For security purposes, we need to try to avoid the [event-stream incident](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident). I'd advise going with people you can trust and/or have experience working with.

**Comment by jeremymailen** [comment]
Thank you @shyiko! Bringing a project this popular and useful into the world is no small feat ❤️. The community has benefited from your hard work.

I'd be able to help a little with maintenance alongside a team of others if one can be formed. Would you consider moderating for a bit during the transition to provide guidance?

**Comment by Tapchicoma** [comment]
Thank you @shyiko for developing this tool :+1: 

I am with what @JLLeitschuh wrote and will try to support this project with maintenance stuff and possibly developing new features.

**Comment by shyiko** [comment]
Thanks everyone!
Project is moving to @pinterest! Stay tuned!
