### ISSUE TITLE
Indentation rule is incomplete

### ISSUE THREAD

**Issue by shyiko** [shyiko/ktlint#338]
[IndentationRule](https://github.com/shyiko/ktlint/blob/master/ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/IndentationRule.kt) is too basic. All it does is check that indentation is a multiple of `indent_size`. We need to rewrite the rule to calculate & adjust the indentation in a single pass over AST. 

Related Issues: #141 #285 #294 (PR; came close but appears to be abandoned) #296 #324

**Comment by shyiko** [comment]
[0.31.0](https://github.com/shyiko/ktlint/blob/master/CHANGELOG.md#0310---2019-03-10)

**Comment by gnomeria** [comment]
Is it still experimental in 0.35 ? Somehow I couldn't autoformat any indentation rules

**Comment by Tapchicoma** [comment]
Yes, it is still experimental: https://github.com/pinterest/ktlint/blob/master/ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/IndentationRule.kt

**Comment by kozaxinan** [comment]
New experimental indentation rule still doesn't check continuation_indent_size. Is that intended? It would be nice to have indent_size = 2 and continuation_indent_size = 4. It is not possible at the moment. Is there any plan to support different continuation_indent_size?

**Comment by Tapchicoma** [comment]
@kozaxinan I would propose to open a separate issue for your problem
