### ISSUE TITLE
Json format is not recognized when outputting a report

### ISSUE THREAD

**Issue by iccen8** [shyiko/ktlint#346]
I was testing outputting an analysis report on Windows. When I ran the following code: 

java -jar ktlint-all.jar --reporter=json,output="C:\Users\david\Documents\KotlinProject\SimpleGallery\Simple-Gallery\app\rpt_test.json"

I got the following error: 
Error: reporter "json" wasn't found (available: plain)

BTW, I am able to run:
java -jar ktlint-all.jar --reporter=plain?group_by_files,output="C:\Users\david\Documents\KotlinProject\SimpleGallery\Simple-Gallery\app\rpt_test.txt"

**Comment by iccen8** [comment]
"--reporter=<reporters>  A reporter to use (built-in: plain (default), plain?group_by_file, json, checkstyle)."

This guidance was shown when I used argument "--help", hence I assumed "--reporter=json" should be a valid argument input.

**Comment by shyiko** [comment]
Thank you for reporting! Fixed in https://github.com/shyiko/ktlint/commit/6e667a0f7fb4806c3c682bdc10e677538c555296.

**Comment by iccen8** [comment]
> Thank you for reporting! Fixed in [6e667a0](https://github.com/shyiko/ktlint/commit/6e667a0f7fb4806c3c682bdc10e677538c555296).

Works now. Thank you!
