### ISSUE TITLE
Bundled up gradle plugin (something to make you aware of)

### ISSUE THREAD

**Issue by JLLeitschuh** [shyiko/ktlint#35]
I wanted to allow users a bit more control over their build so I wrapped up your tool in a gradle plugin that I'll continue to develop as time goes on.

https://github.com/JLLeitschuh/ktlint-gradle

@shyiko I'm happy to add you as a contributor if you are interested.

**Comment by shyiko** [comment]
@JLLeitschuh Nice :+1:! Let me know when it's finished and published to Maven Central (jcenter or whatever your poison is). Add I'll gladly add a link to the readme.md.

> @shyiko I'm happy to add you as a contributor if you are interested.

Thank you for the offer but I think there is no need. Fork button is one click away ;)
