### ISSUE TITLE
How to use continuation ident for parameters?

### ISSUE THREAD

**Issue by emartynov** [shyiko/ktlint#350]
Hi guys,

How to have a setting similar to next:
<img width="735" alt="screenshot 2019-03-03 at 19 07 04" src="https://user-images.githubusercontent.com/295424/53699470-d498c700-3de8-11e9-8cb6-045581b8f74f.png">

**Comment by arturbosch** [comment]
There is an option in the .editor-config file. However it is not used anymore because the official kotlin style guide says to just use four spaces for continious indentation (https://github.com/yole/kotlin-style-guide/issues/38).

**Comment by emartynov** [comment]
I don't remember if it defaulted or we set `use continuation ident` during team decision.

As for now, IDE adds 12 spaces to a method param on the new line = 4 from ident and 8 from continuation ident.

**Comment by shyiko** [comment]
I'm sorry but both Android Style Guide and Kotlin Coding Conventions do not mention continuation indent size and so it's unlikely to be supported. 
The recommendation is to set `continuation_indent_size` = `indent_size` = `4`.
