### ISSUE TITLE
Interested in creating an organization?

### ISSUE THREAD

**Issue by JLLeitschuh** [shyiko/ktlint#38]
Do you want to create a small organization that holds the ktlint project and gradle plugin?
As many projects end up stagnating when the core developers move on to other things, creating an organization makes it easier to give more people control over maintaining projects.

Pros:
 - If either of us drops off the face of the earth then the other can continue to maintain or at least merge PR's.
 - Combined access for new contributors that become interested in the projects and we want to provide maintainer access to.

Thoughts?

I was thinking just name the organization `ktlint`. We'd both transfer ownership of our projects over to this org and update our readme's to reflect the link changes.

**Comment by shyiko** [comment]
Hi Jonathan.

I was hoping to do that once ktlint gets a little bit more traction. Right now it's just too low to bother.

Anyhow, I just wrote a message to GitHub Support asking whether https://github.com/ktlint can be transferred under our control as an org (per https://help.github.com/articles/name-squatting-policy/). Let's see how it goes.

**Comment by JLLeitschuh** [comment]
Sounds good!

**Comment by shyiko** [comment]
Alright, so the org is ours. I've created https://github.com/ktlint/ktlint.github.io which is what is served when you open [ktlint.github.io](https://ktlint.github.io/) (source is a mess as I didn't want to spend more then a day on it but whatever). 

Lets see whether we can get decent adoption numbers and then transfer the projects.

**Comment by JLLeitschuh** [comment]
I love it. The site looks great!
