### ISSUE TITLE
Apply recommendations from yole/kotlin-style-guide

### ISSUE THREAD

**Issue by shyiko** [shyiko/ktlint#4]
https://github.com/yole/kotlin-style-guide

**Comment by pardonut** [comment]
Shouldn't we be targeting this now?

https://github.com/JetBrains/kotlin-web-site/blob/yole/styleguide/pages/docs/reference/coding-conventions.md

**Comment by shyiko** [comment]
@pardonut Thank you for the link! I wasn't aware of it. Definitely something to look into. 
On a separate note, I'm sorry hear about your 2FA recovery ordeal :cry:

**Comment by pardonut** [comment]
Hah, yeah well I guess I learned a valuable lesson.

**Comment by Tapchicoma** [comment]
FYI: Styleguide for Kotlin from Google: https://android.github.io/kotlin-guides/style.html

**Comment by shyiko** [comment]
@Tapchicoma thank you!

**Comment by pardonut** [comment]
Probably want to have some sort of rulesets in case people prefer Google's over the official Kotlin style.

**Comment by shyiko** [comment]
@pardonut At first glance, it looks like Google style guide is compatible (unless I'm missed something) with the one enforced by ktlint (some of the rules are not yet enforced but it's a matter of time) (`ktlint --apply-to-idea` needs to be updated to detect .editorconfig's continuation_indent_size value but other than that it looks like we're good for now).

**Comment by twaddington** [comment]
KotlinConf 2017 just wrapped and there are now some additional style docs:

- https://android.github.io/kotlin-guides/style.html
- https://github.com/JetBrains/kotlin-web-site/blob/yole/styleguide/pages/docs/reference/coding-conventions.md

**Comment by vanniktech** [comment]
Is there anything specific missing? Otherwise I'd close this and do necessary changes when they are requested.

**Comment by shyiko** [comment]
@vanniktech this ticket is pretty much a reminder that there are a lot of rules that still need to be implemented (like https://github.com/android/kotlin-guides/blob/master/style.md#empty-blocks or https://github.com/android/kotlin-guides/blob/master/style.md#expressions). We should probably create an issue for each missing rule (if anybody feels like helping I would appreciate it) and close this (but not until it's done).

**Comment by vanniktech** [comment]
Then let's separate, close this and implement each thing on it's own.

**Comment by Tapchicoma** [comment]
And here it is official coding convention: https://kotlinlang.org/docs/reference/coding-conventions.html

**Comment by mkulak** [comment]
Would love to see ktlint consistent with official JetBrains style guide.
