### ISSUE TITLE
Mention spotless plugin in readme

### ISSUE THREAD

**Issue by JLLeitschuh** [shyiko/ktlint#41]
The [spotless](https://github.com/diffplug/spotless/tree/master/plugin-gradle) gradle plugin is pretty solid.

The only reason that I wrote my plugin was I needed it to be standalone.
I'm using spotless in a new project and it works really nicely.

**Comment by shyiko** [comment]
Thank you. I should have done that a long time ago. 6728f86a3f77e3d510be28ca441f3defe9c65dc6

**Comment by shyiko** [comment]
@nedtwigg
