### ISSUE TITLE
Standard modifier order?

### ISSUE THREAD

**Issue by swankjesse** [shyiko/ktlint#42]
The official style guides are quiet about whether we should say `override public` or `public override`.

Does ktlint wanna enforce one true order?

I made up a standard order for KotlinPoet, but I’m not particular to it.
https://github.com/square/kotlinpoet/blob/master/src/main/java/com/squareup/kotlinpoet/KModifier.kt

**Comment by shyiko** [comment]
Hi @swankjesse. Absolutely. https://github.com/yole/kotlin-style-guide/issues/3 is still open but I think it's pretty safe to add this rule to the ktlint-ruleset-standard. Thank you for drawing my attention to it.

**Comment by shyiko** [comment]
Implemented in [0.7.0](https://github.com/shyiko/ktlint/blob/master/CHANGELOG.md#070---2017-05-28). Order (same as in https://github.com/yole/kotlin-style-guide/issues/3) is defined [here](https://github.com/shyiko/ktlint/blob/master/ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/ModifierOrderRule.kt#L35).

I'd appreciate if you could take a vote in https://github.com/shyiko/ktlint/issues/43. Cheers!

**Comment by shyiko** [comment]
@swankjesse one more thing - https://ktlint.github.io/ :)
