### ISSUE TITLE
Imports only used in docs

### ISSUE THREAD

**Issue by gabrielittner** [shyiko/ktlint#46]
When an import is only used in square brackets in the docs it will get removed by ktlint. For example:
```kotlin
package com.example

import android.provider.CalendarContract.Colors

/**
 * [Colors]
 */
class Foo
```
will become:

```kotlin
package com.example

/**
 * [Colors]
 */
class Foo
```

IntelliJ itself shows the import as used (or not as unused).

**Comment by shyiko** [comment]
@gabrielittner Thank you! I'll take care of it.

**Comment by shyiko** [comment]
On a second thought, it might be what we want. The thing is `Foo` class is not technically using `Colors`. It does reference it the docs but that doesn't mean that Foo has hard (compile) dependency on `Colors`. Kotlin supports alternatives that don't require `import`s:
```markdown
[Colors](android.provider.CalendarContract.Colors)

[android.provider.CalendarContract.Colors]
```
What do think?

**Comment by gabrielittner** [comment]
I'm not sure what's the best solution here. In the case where I've run across it, the imported class is used a ton in the docs and using it without import adds a lot of noise. If yo decide to keep removing the import it would be nice to at least get a warning or something, because without the import all the links will be broken.

**Comment by vRallev** [comment]
I'm running into the same issue and I'd prefer if the import would be allowed in this case for the same reason. It would add a lot of noise to reference the full path everywhere.

**Comment by shyiko** [comment]
@gabrielittner @vRallev fair enough. Fixed in [0.7.1](https://github.com/shyiko/ktlint/blob/master/CHANGELOG.md#071---2017-05-29) (Maven Central sync might take up to ~25 minutes). :tada:

**Comment by vRallev** [comment]
The new version works nicely. Thanks!

**Comment by gabrielittner** [comment]
Also working here. Thank you
