### ISSUE TITLE
Support custom output formatter (reporters)

### ISSUE THREAD

**Issue by shyiko** [shyiko/ktlint#53]

**Comment by cprieto** [comment]
I will love support for results in xml, json, etc... or a way to _extend klint_ so we can have a custom output format.

The extensibility point will be preferable so in this way it will be open for new build engines and report formats.

**Comment by shyiko** [comment]
@cprieto done. Check out [0.9.0](https://github.com/shyiko/ktlint/releases/tag/0.9.0) release notes and code examples in the [README](https://github.com/shyiko/ktlint). :balloon:
