### ISSUE TITLE
Problem with try-catch

### ISSUE THREAD

**Issue by vRallev** [shyiko/ktlint#57]
If I surround some code with a try-catch, then ktlint doesn't accept the default style.
```kotlin
try {
    someMethod()
} catch(e: Exception) {
}
```
ktlint reports a missing space after the catch, it wants `} catch (e: Exception) {`.

Is this by design? I couldn't find any hint somewhere that the space is recommended.

**Comment by shyiko** [comment]
Hi @vRallev. 

Yeah, this is an interesting one. Whenever IDEA is trying to format a block of code it's using a mix of Java's and Kotlin's "Editor > Code Style". In this case it looks like a bug on Intellij side as it should have been covered by "Editor > Code Style > Java > Spaces > 'catch' parantheses" (which is set to true by default). So to answer your question - yes there should be a space (a rule of thumb - keywords (if, while, etc.) should be separated by space on both sides).

**Comment by vRallev** [comment]
Sounds reasonable. Thanks for clarifying that for me!
