### ISSUE TITLE
When case formatting

### ISSUE THREAD

**Issue by adelnizamutdinov** [shyiko/ktlint#58]
ktlint says I have unnecessary spaces here

```kotlin
when {
    true         -> 1
    true && true -> 2
    else         -> 3
}
```

but these are not unnecessary

**Comment by shyiko** [comment]
@adelnizamutdinov ktlint does not allow vertical alignment [on purpose](https://github.com/yole/kotlin-style-guide/issues/23#issuecomment-243693320)* (there are exceptions like class/function arg list or comments but `when` expression is not one of them). Intellij IDEA formatter (with default settings) is more or less doing the same.
