### ISSUE TITLE
Companion object order

### ISSUE THREAD

**Issue by samarjan92** [shyiko/ktlint#63]
What do you think about companion object order in class? I prepared a rule that verify that position of companion object is first in class

**Comment by vanniktech** [comment]
Personally I'd prefer it to be the last one.

**Comment by arturbosch** [comment]
According to https://github.com/yole/kotlin-style-guide/issues/5 companion objects should be placed last ...

**Comment by shyiko** [comment]
@arturbosch +1. 

Considering that 
- [Android Style Guide](https://android.github.io/kotlin-guides/style.html#class-member-ordering) [advocates logical ordering](https://github.com/android/kotlin-guides/issues/11) (which I'm personally in favor of)
- I've seen plenty of situations where companion object contains code that users would want to see first (not last)
- and I'd like to avoid rules with relatively complex logic that can have negative impact on other rules (moving code around given current kotlin compiler API isn't exactly straightforward) I propose we close this ticket (at least for now).

**Comment by sagar-nickelfox** [comment]
@DSamaryan how did you detected the companion object? Can you share the code of that detector?

**Comment by DSamaryan** [comment]
@sagar-nickelfox 
Sorry, I already lost that code

**Comment by sagar-nickelfox** [comment]
> @sagar-nickelfox Sorry, I already lost that code

Oh, it's alright.
