### ISSUE TITLE
Doesn't handle escaped imports properly

### ISSUE THREAD

**Issue by dstarcev** [shyiko/ktlint#7]
It says the first import is unused. It's wrong. Quick fix is there https://github.com/shyiko/ktlint/pull/6
```kotlin
import org.mockito.Mockito.`when`
import org.mockito.Mockito.mock

class LinterFailure {
    fun foo() {
        val bar = mock(LinterFailure::class.java)
        
       `when`(bar.foo())
    }
}
```

**Comment by shyiko** [comment]
Thank you for the PR! Included in 0.1.2 (which should become available through Maven Central within the next 2 hours).
