### ISSUE TITLE
Add project-wide suppression for UnexpectedIndent rule

### ISSUE THREAD

**Issue by SUPERCILEX** [shyiko/ktlint#70]
This one issue is blocking me from adopting `ktlint`. I get that everything should be 4 spaces, but sometimes that just looks terrible. Code that makes `ktlint` happy:
```kt
Snackbar.make(
        activity.findViewById<View>(R.id.root),
        R.string.no_connection,
        Snackbar.LENGTH_LONG)
        .show()
```

Code that makes developers happy:
```kt
Snackbar.make(activity.findViewById<View>(R.id.root),
              R.string.no_connection,
              Snackbar.LENGTH_LONG)
        .show()
```

**Comment by shyiko** [comment]
Supported in [0.10.0](https://github.com/shyiko/ktlint/releases/tag/0.10.0). 
> .editorconfig
```
[*.{kt,kts}]
indent_size=unset
```

**Comment by SUPERCILEX** [comment]
@shyiko Awesome!
