### ISSUE TITLE
Not working in IntelliJ IDEA

### ISSUE THREAD

**Issue by rmaes4** [shyiko/ktlint#74]
Here's what I did: I downloaded ktlint using the how to in the readme. I copied the executable to my IntelliJ project root. I ran the command to use ktlint with IntellIJ and pressed "y" for the prompt. It all appeared to work fine. When I build my project however, I don't see anything new.

Running Mac OS X

**Comment by shyiko** [comment]
Hi @rmaes4.

[ktlint --apply-to-idea](https://github.com/shyiko/ktlint#option-1-recommended) is just an automation of [option 2](https://github.com/shyiko/ktlint#option-2) / [option 3](https://github.com/shyiko/ktlint#option-3). Its sole purpose is to make IDEA's "Command+Option+L" (Reformat code) and "Control+Option+O" (Optimize Imports) behave as close as possible to `ktlint --format`. That's all there is to it.

You can check that project settings were indeed updated by going to "Settings -> Editor -> Code Style -> Kotlin". It should look similar to:  

![img-2017-08-13-201226](https://user-images.githubusercontent.com/370176/29257173-ae79088e-8064-11e7-8fad-d73bf297b551.png)
