### ISSUE TITLE
Support .editorconfig's continuation_indent_size

### ISSUE THREAD

**Issue by JLLeitschuh** [shyiko/ktlint#76]
According to ktlint both of these are valid:
```kotlin
fun Project.`spotless`(configure: com.diffplug.gradle.spotless.SpotlessExtension.() -> Unit = {}) =
    extensions.getByName<com.diffplug.gradle.spotless.SpotlessExtension>("spotless").apply { configure() }
```
```kotlin
fun Project.`spotless`(configure: com.diffplug.gradle.spotless.SpotlessExtension.() -> Unit = {}) =
        extensions.getByName<com.diffplug.gradle.spotless.SpotlessExtension>("spotless").apply { configure() }
```

Similarly both of these are valid:
```kotlin
val someSet = setOf(
    "a"
)
```
```kotlin
val someSet = setOf(
        "a"
)
```

**Comment by shyiko** [comment]
Yeah, support for .editorconfig's `continuation_indent_size` is not implemented yet ([IndentationRule](https://github.com/shyiko/ktlint/blob/master/ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/IndentationRule.k)). It would be very nice to have, though.

**Comment by JLLeitschuh** [comment]
The link you posted is dead.

**Comment by shyiko** [comment]
@JLLeitschuh (updated)
