### ISSUE TITLE
Error:Execution failed for task ':app:spotlessKotlin'. > Unexpected indentation (2) (it should be multiple of 4)

### ISSUE THREAD

**Issue by iamzhouu** [shyiko/ktlint#78]
.editorconfig >>

root = true

[*]
charset = utf-8
indent_style = space
indent_size = 2
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false

[*.json]
insert_final_newline = ignore

[*.java]
max_line_length = 100
continuation_indent_size = 4

[*.{kt,kts}]
max_line_length = 100
indent_size = 4
continuation_indent_size = 8

[gradlew.bat]
end_of_line = crlf

apply plugin: 'com.diffplug.gradle.spotless'

spotless {
  enforceCheck false

  java {
    //licenseHeaderFile 'spotless.license.java'
    googleJavaFormat()
  }

  kotlin {
    //licenseHeaderFile '../spotless/copyright.kt'
    target "**/*.kt"
    ktlint('0.9.2')
  }
}

**Comment by shyiko** [comment]
`indent_size` is set to `4` (under `[*.{kt,kts}]`) and yet somewhere in one of the files you are linting indentation is "  " (2) instead of "    ".
