### ISSUE TITLE
Coding problem？

### ISSUE THREAD

**Issue by cyw3** [shyiko/ktlint#82]
ktlint path/to/project

![image](https://user-images.githubusercontent.com/11549103/30734664-b92ab944-9fae-11e7-80df-98ea202ba987.png)

**Comment by shyiko** [comment]
Hi @cyw3. This is interesting. How about `java -jar ktlint path/to/project`, does it work? Also, what is your OS? (FYI: when you execute ktlint directly [this is what happens](https://github.com/brianm/really-executable-jars-maven-plugin/blob/master/src/main/java/org/skife/waffles/ReallyExecutableJarMojo.java#L171)).

**Comment by cyw3** [comment]
No, it does not work. My OS is macOS Sierra 10.12.6

**Comment by shyiko** [comment]
Just checked on macOS Sierra 10.12.6 - everything seems to be in order (I tried both downloading ktlint directly with curl and installing through brew). 
There must be something wrong with you local environment (if `java -jar ktlint --version` produces the same output as you originally specified I'd check `java` first).

**Comment by cyw3** [comment]
And it does not work in windows 7. and my project files have some Chinese words. I think it can't handle with Chinese.

**Comment by shyiko** [comment]
@cyw3 any chance you can provide a sample (kotlin file) which ktlint fails to lint?

**Comment by cyw3** [comment]
Oh, sorry. I'm wrong. it is not because the Chinese words. It is because of the .exe files or .png files in my project, for example:
![image](https://user-images.githubusercontent.com/11549103/30797276-eeb51374-a207-11e7-929c-6585fabbee67.png)
![image](https://user-images.githubusercontent.com/11549103/30797296-01646b46-a208-11e7-8698-a9eda008e65b.png)

However, ktlint can't know which file is .kt file if the project is too big to record every .kt file???

**Comment by shyiko** [comment]
I see. I think the problem is that `ktlint path/to/project` is effectively `ktlint path/to/project/**/*`. What you need is `ktlint path/to/project/**/*.kt`. Let me know if it works (btw, check out `ktlint --help` for more examples).
