### ISSUE TITLE
Naming style - Allow methods names like `not concatenated text`

### ISSUE THREAD

**Issue by gmariotti** [shyiko/ktlint#84]
Because Kotlin allows having methods starting and ending with ` , it's now popular to write test like normal text instead of using camel case. Would this be possible?

**Comment by shyiko** [comment]
Hi @gmariotti. This naming style is not prohibited (ktlint should not complain). Is it not the case?

**Comment by gmariotti** [comment]
Intellij complains because it says that the pattern `[a-z][A-Za-z\d]*` for `Function naming convention` is not respected, and this value is set using `ktlint --apply-to-idea`. Maybe I'm doing something wrong, am I?

**Comment by shyiko** [comment]
`Function naming convention` is not set by `ktlint --apply-to-idea` (you can check that [here](https://github.com/shyiko/ktlint/tree/master/ktlint-intellij-idea-integration/src/main/resources/config)). In fact I can't find anything resembling `[a-z][A-Za-z\d]* check Function naming convention` in IDEA (2017.2). Can you please attach a screenshot of the error (and location of the setting)?

**Comment by gmariotti** [comment]
It seems like that is an IntelliJ default, but only now is starting to complain about it. I thought it was something that ktlint was changing but apparently is not. Sorry to bother you.

**Comment by shyiko** [comment]
@gmariotti no worries. For the record, I just upgraded to 2017.4 and I still don't see "Function naming convention" check in IDEA. You might have a 3rd party plugin enabled (e.g. sonarqube) that I don't. Let me know if you track it down.
