### ISSUE TITLE
Extract linter to library dependency

### ISSUE THREAD

**Issue by pardom** [shyiko/ktlint#9]
I've been looking for a Kotlin linter for two reasons, one of which is accomplished with this library. The other reason I want a Kotlin linter is to create a companion linter for FP libraries. This linter would do things like:
* Enforce use of `val`.
* Require functions to be pure.
* Use `Maybe` instead of nullables when the type exists.

For this reason, it would be useful to decouple the rules from the base linter/parser. Implementing libraries could then supply their own rules. Thoughts?

**Comment by shyiko** [comment]
@pardom Sure. I can make [KtLint.lint/format](https://github.com/shyiko/ktlint/blob/master/src/main/kotlin/com/github/shyiko/ktlint/KtLint.kt#L90) public. That will allow to specify custom [rules](https://github.com/shyiko/ktlint/tree/master/src/main/kotlin/com/github/shyiko/ktlint/rule) & handle any violations any way you like.  

Let me know if I'm missing something. Thanks!

P.S.
ktlint is available through Maven Central

```
<dependency>
    <groupId>com.github.shyiko</groupId>
    <artifactId>ktlint</artifactId>
    <version>0.1.2</version>
</dependency>
```

P.P.S.
I'm also considering adding "presets" (additional (more restrictive) set of rules) to ktlint. FP could potentially be one them (in fact I'm pretty sure I would use it myself). I'm always open to collaboration and so if you're interested - I can definitely see FP rules included into ktlint (`ktlint --fp`).

**Comment by pardom** [comment]
I was thinking of something a bit more abstract. For example:

```
├── ktlint-core
│   └── src
│       └── rule
├── ktlint-standard
│   └── rule
└── ktlint-functional
    └── rule
        
```

`ktlint-core` is the base project, and other projects like `ktlint-standard` and `ktlint-functional` add `ktlint-core` as a dependency, and provide only the rules. Or the can compose one another, e.g. `ktlint-functional` could depend on `ktlint-standard`.

**Comment by shyiko** [comment]
Where does CLI (Main.kt) go? some kind of 'ktlint-cli' module which wires all together?

**Comment by pardom** [comment]
Perhaps. I'm not exactly sure what the mechanism would be to wire it all up, off hand. Making the parser open for extension is the goal, though.

**Comment by shyiko** [comment]
@pardom jsyk: this thing is in progress. It might take several days before it's ready (due to the insane the schedule this week) but it's coming.

**Comment by pardom** [comment]
Cool, no hurry. I'd be happy to contribute, too.

**Comment by shyiko** [comment]
@pardom 0.2.0 is finally out :tada:. readme.md & chanelog.md updated. ktlint was broken into multiple modules but more importantly it now supports for 3rd party rulesets. Please check the readme.md ("Usage" and "Creating a ruleset" sections) and let me know if something isn't clear or simply doesn't make sense. Thank you!
