### ISSUE TITLE
Thoughts on enforcing "Insert imports for nested classes"?

### ISSUE THREAD

**Issue by twaddington** [shyiko/ktlint#90]
IntelliJ has a preference in "Code Style → Kotlin → Imports" called "Insert imports for nested classes."

This changed the default import behavior from this:

```kotlin
import android.support.v7.widget.RecyclerView

class VerticalOffsetItemDecoration() : RecyclerView.ItemDecoration() {
    // ...
}
```

To this:

```kotlin
import android.support.v7.widget.RecyclerView
import android.support.v7.widget.RecyclerView.ItemDecoration

class VerticalOffsetItemDecoration() : ItemDecoration() {
    // ...
}
```

The default behavior optimizes for fewer imports. If you've already imported `RecyclerView` a new import will not be added.

However, the second optimizes for horizontal line length. It will also add an explicit import for `ItemDecoration`.

I personally prefer and recommend the second option, but I'm curious what others think.

**Comment by shyiko** [comment]
I'd say it depends. Sometimes you want to make connection between the nested and containing classes explicit (e.g. Map.Entry) (especially considering that inner classes tend to have more generic names), other times it doesn't matter. I think it's up to developer to decide, not ktlint.
