### ISSUE TITLE
Max line length rule is enforced but auto-formatting isn't supported?

### ISSUE THREAD

**Issue by aaronhe42** [shyiko/ktlint#96]
It's cool `ktlint` can honor `max_line_length` in the `.editorconfig` file, but the auto-formatting doesn't seem to be supported?

For example, if I have this `Person.kt` file:
```
class Person(id: Int, firstName: String, lastName: String, middleName: String?, age: Int, email: String?, phoneNumber: String?, twitterHandle: String?)
```

Then when I do `ktlint -F Person.kt`, it would just complain `Exceeded max line length (120)` without formatting it.

**Comment by shyiko** [comment]
Hi @aaronhe42. You're right, right now `ktlint -F` won't split the line when `max_line_length` is exceeded. This is somewhat related to https://github.com/shyiko/ktlint/issues/76#issuecomment-322309240.

**Comment by JLLeitschuh** [comment]
Is `max_line_length`documented as supported somewhere in the documentation??

**Comment by shyiko** [comment]
@JLLeitschuh only here - https://github.com/shyiko/ktlint#editorconfig

**Comment by ntsim** [comment]
@shyiko do you have have plans to support this formatting? I gave the code a little look and it seems like most of the work is already done for this in the `parameter-list-wrapping` rule.  If there isn't some other reason for holding back, I could push up a PR for this?

**Comment by shyiko** [comment]
Hi @ntsim. No reasons other than not enough time :) If you send a PR I'd gladly merge it in.
