### ISSUE TITLE
Blank lines exceptions

### ISSUE THREAD

**Issue by vRallev** [shyiko/ktlint#98]
With the upgrade to `0.11.1` some styles don't work anymore according to #65. But I find them really useful, e.g.
```kotlin
if (something) {
    doSomething1()
    doSomething1()
    doSomething1()
    doSomething1()

} else if (something1) {
    doSomething1()
    doSomething1()
    doSomething1()
    doSomething1()

} else {
    doSomething1()
    doSomething1()
}
```
I find the empty line useful for a better separation especially in longer chained if-else statements. Is there something I could do to allow this?

**Comment by shyiko** [comment]
How about 

```kotlin
when {
    something -> {
        doSomething1()
        doSomething1()
        doSomething1()
        doSomething1()
    }
    something1 -> {
        doSomething1()
        doSomething1()
        doSomething1()
        doSomething1()
    }
    else -> {
        doSomething1()
        doSomething1()
    }
}
```

or better yet

```kotlin
when {
    something -> handleSomething()
    something1 -> handleSomething1()
    else -> handleSomethingElse()
}
```
?

Generally, if I find myself in a situation where a blank line is required to make code readable it usually means that it's too long and should be split. 

P.S. https://github.com/shyiko/ktlint#how-do-i-suppress-an-error might be of interest but I strongly advise against it.
 
(I'm closing this issue as nothing is really broken but feel free to continue the discussion)

**Comment by vRallev** [comment]
Another example is a try-catch with multiple catch statements. There it becomes ugly :/
